#!/bin/bash
#
# Copyright (C) eSrijan Innovations Private Limited
#
# Author: Anil Kumar Pugalia <anil_pugalia@eSrijan.com>
#
# Licensed under: JSL (See LICENSE file for details)
#

if [ $# -ne 2 ]
then
	echo "Usage: $0 <tgz_file_to_package> <package_file>"
	exit 1
fi

content_file=$1
package_file=$2
out_dir=.`basename ${content_file} .tgz`

cat > ${package_file} <<PACKAGE_HDR
#!/bin/bash

mkdir -p ${out_dir}
start_line_of_tgz=\$((\`grep -an "^TGZ_CONTENT$" \$0 | cut -d: -f1\` + 1))
tail -n+\${start_line_of_tgz} \$0 > ${out_dir}/.tmp.tgz
cd ${out_dir}
tar -zxvf .tmp.tgz > /dev/null
rm -f .tmp.tgz
echo "To proceed with firmware upgrade to v${FW_VER}, please do the following:"
echo "1. Connect the LDDK to this computer with the USB cable provided along with it."
echo "2. Switch on the LDDK by pressing the power switch on the LDDK."
echo "3. Press the white DOWNLOAD & red RESET buttons together."
echo "4. First release the RESET, and then the DOWNLOAD button."
echo "5. If green PGM LED starts blinking, press any key to proceed."
echo "Otherwise, repeat the above sequence 3 to 5."
read
./bootloadHID -r ./usbdev.hex 2> /dev/null
retval=\$?
if [ \${retval} != 0 ]
then
	./bootloadHID --v2 -r ./usbdev.hex
	retval=\$?
	if [ \${retval} = 0 ]
	then
		echo "WARNING: Complete I/O access may need bootloader upgrade"
	fi
fi
cd ..
rm -fr ${out_dir}
if [ \${retval} = 0 ]
then
	echo "Upgrading to firmware v${FW_VER} completed successfully."
else
	echo "Upgrading to firmware v${FW_VER} failed."
fi
exit \${retval}
TGZ_CONTENT
PACKAGE_HDR
cat ${content_file} >> ${package_file}

chmod +x ${package_file}
